[tool.flit.metadata]
module = "RandomCarrot"
author = "Mark Pavlenko"
author-email = "markpavlenkos@gmail.com"
home-page = "https://github.com/MarkPavlenko/RandomCarrot"
requires-python = ">=3.6"
license = "MIT"

[tool.flit.metadata.classifiers]
Development Status = "5 - Production/Stable"
License = "OSI Approved :: MIT License"
Programming Language = "Python :: 3"
Operating System = "MacOS"
Intended Audience = "Developers"