name: Publish Package to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: MacOS

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.markusia69 }}
          TWINE_PASSWORD: ${{ secrets.RomaKava0114 }}
        run: twine upload dist/*